---
kind: pipeline
type: docker
name: build-dry-run
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/redpencilio/redpencil}/${DRONE_REPO_NAME%-service}
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/redpencilio/redpencil}/${DRONE_REPO_NAME%-service}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/redpencilio/redpencil}/${DRONE_REPO_NAME%-service}
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: AMvGJid/ng9JiiDyB085NJ2AbJgrdEBHO1VZtTSVgKvvO1w4UW/F
---
kind: secret
name: docker_password
data: +72RVc0xlwUDgr0x5JzILUuMr4E2e0xesrTd9EmnHxFEfsXd/m+cWsIKC6xvy4mdDIE9cLaA3gGvRa5UtGtPqw==
---
kind: secret
name: npm_access_token
data: d7368bba-01b6-4fc8-aa34-a4856cb16e28
---
kind: signature
hmac: d91a987bae5ac5c74b37f5b11e1568e4d511c725ad12d593a22c54e204be79fe

...
